# Generated by Django 4.1.3 on 2022-11-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbId', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
                ('image', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
    ]
