# Generated by Django 4.1.3 on 2022-11-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='awards',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
