# Generated by Django 4.1.3 on 2022-11-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='https://i.imgur.com/1t8xewY.png', max_length=200),
        ),
    ]
